In [2]:
#to check the version of anaconda
import numpy as np
print(np.__version__)

1.25.1


In [2]:
#to access array
import numpy as np
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [15]:
#to access datatypes of array
import numpy as np
arr = np.array([1,2,3,4])
print(arr.dtype)

int32


In [16]:
#1-D array
import numpy as np
arr = np.array(42)
print(arr)

42


In [10]:
#2-D array
import numpy as np
arr = np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
#3-D array
import numpy as np
arr = np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
print(arr)

[[[ 1  2  3]
  [ 4  5  6]]

 [[11 12 13]
  [14 15 16]]]


In [17]:
#find dimension of numpy array
a = np.array(42)
b = np.array([1,2,3,4,5])
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
# Save Function in numpy
import numpy as np 
a = np.array([1,2,3,4,5])
np.save('outfile',a)

In [1]:
# load function
import numpy as np
b = np.load("outfile.npy")
print(b)

[1 2 3 4 5]


In [2]:
import numpy as np
a = np.array([1,2,3,4,5])
print(type(a))
print(a.dtype)
np.savetxt("out.txt",a)
b = np.loadtxt("out.txt")
print(b)
print(type(b))
print(b.dtype)

<class 'numpy.ndarray'>
int32
[1. 2. 3. 4. 5.]
<class 'numpy.ndarray'>
float64


In [3]:
import numpy as np
arr = np.arange(1,10,2)
print("ELements of array:",arr)
arr1 = arr[np.array([4,0,2,-1,-2])]
print("Indexed Elements of array arr:",arr1)

ELements of array: [1 3 5 7 9]
Indexed Elements of array arr: [9 1 5 9 7]


In [7]:
#1-D array
import numpy as np
arr1 = np.arange(4)
print("Array arr1:",arr1)
print("Element at index o of arri is: ",arr1[0])
print("Element at index 1 of arr1 is: ",arr1[1])

Array arr1: [0 1 2 3]
Element at index o of arri is:  0
Element at index 1 of arr1 is:  1


In [8]:
#2-D array
import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("Element at eth row and eth column of arr1 is:",arr1[0,0])
print("Element at 1th row and 2th column of arr1 is:",arr1[1,2])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Element at eth row and eth column of arr1 is: 0
Element at 1th row and 2th column of arr1 is: 6


In [9]:
#3-D array
import numpy as np
arr=np.arange(12)
arr1 = arr.reshape(2,2,3)
print("Array arr1 :\n",arr1)
print("ELement:",arr1[1,0,2])

Array arr1 :
 [[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
ELement: 8


In [13]:
# Slicing a 1D array
import numpy as np
arr = np.arange(6)
print("Array arr:",arr)
print("Sliced element of array: ",arr[1:5])
print("Sliced element of array: ",arr[-5:-1])


Array arr: [0 1 2 3 4 5]
Sliced element of array:  [1 2 3 4]
Sliced element of array:  [1 2 3 4]


In [20]:
# Slicing in 2D array
import numpy as np
arr = np.arange(12)
arr1 = arr.reshape(3,4)
print("Array arr1:\n",arr1)
print("\n")
print("Sliced element of 1st row and 1st column upto last column \n: ",arr1[1:,1:4])

Array arr1:
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


Sliced element of 1st row and 1st column upto last column 
:  [[ 5  6  7]
 [ 9 10 11]]


In [21]:
# Broadcasting in numpy

import numpy as np
a = np.array([[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]])
b = np.array([1.0,2.0,3.0])

print("First array")
print(a)
print("\n")

print("Second array")
print(b)
print("\n")

print("First array + Second array")
print(a + b )


First array
[[ 0.  0.  0.]
 [10. 10. 10.]
 [20. 20. 20.]
 [30. 30. 30.]]


Second array
[1. 2. 3.]


First array + Second array
[[ 1.  2.  3.]
 [11. 12. 13.]
 [21. 22. 23.]
 [31. 32. 33.]]


In [22]:
#structured array
import numpy as np
a = np.array([('Sana',2,21.0),('Mansi',7,29.0)],
             dtype=[('name',(np. str_, 10)),('age',np.int32),('weight',np.float64)])
print(a)

[('Sana', 2, 21.) ('Mansi', 7, 29.)]


In [23]:
# statistical function
# mean
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(arr.mean())

3.5


In [24]:
# statistical function
# median
import numpy as np
arr = np.array([1,2,3,4,5,6])
median = np.median(arr)
print(median)

3.5


In [25]:
# statistical function
# range
import numpy as np
arr = np.array([1,2,3,4,5,6])
range = np.ptp(arr)
print(range)

5


In [26]:
# statistical function
# standard deviation
import numpy as np
arr = np.array([1,2,3,4,5,6])
std = np.std(arr)
print(std)

1.707825127659933
